sudo: false
language: php

php:
  - 7.2
  - 7.3

addons:
  apt:
    packages:
      - parallel

env:
  global:
    - CODACY_PROJECT_TOKEN=931d4f93db8e41d39a3174d5ab84c7ac

cache:
  directories:
  - $HOME/.composer/cache

install:
  - >
    composer install

script:
  - >
    echo;
    echo "Running php lint";
    find . -name \*.php ! -path "./vendor/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
  - >
    echo;
    echo "Running unit tests";
    vendor/bin/phpunit --coverage-clover build/coverage.xml


after_script:
  - >
    vendor/bin/codacycoverage clover build/coverage.xml
